### ISSUE TITLE
DNVM build fails with - The hash <> does not match the expected value

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/dnvm#177]
Git cloned the DNVM locally. Attempted to build the solution locally at the command line running build.cmd (please let me know if this is not the correct approach) and it fails. Full build output:

info: Target default
info: Target pre-clean
info: Target clean
info: Target post-clean
info: Target validate
info: Target initialize
info: Target copy-dnvm
info: Copying dnvm.cmd
info: Copying dnvm.ps1
info: Copying dnvm.sh
info: Updating C:\Git\DNVM\artifacts\dnvm.ps1
info: Updating C:\Git\DNVM\artifacts\dnvm.sh
info: Target compile
info: Target test-compile
info: Target run-ps1-tests
info: Exec
info:   program: powershell
info:   commandline: -ExecutionPolicy RemoteSigned -NoProfile -NoLogo -Command & "C:\Git\DNVM\test\ps1\Run-Tests.ps1
info:   workingdir: C:\Git\DNVM
===== Ensuring Pester is at master =====
git: Your branch is up-to-date with 'origin/master'.
git: Already on 'master'
===== Starting child shell to run =====
===== Wiping old test working area =====
===== Fetching test prerequisites =====
Test prerequisites are corrupt, redownloading.
Test prerequisite https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-win-x64/1.0.0-beta4-11244 failed to download. The hash
'949DAF5DD88396594214FAF43ED3675F637340338CA54715A966A7960257A0CE' does not match the expected value.
At C:\Git\DNVM\test\ps1\_Execute-Tests.ps1:129 char:9
+         throw "Test prerequisite $specificNupkgUrl failed to download. The hash  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Test prerequisi...expected value.:String) [], RuntimeException
    + FullyQualifiedErrorId : Test prerequisite https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-coreclr-win-x64/1.0.0-beta4-11244 failed to download. The hash '9
   49DAF5DD88396594214FAF43ED3675F637340338CA54715A966A7960257A0CE' does not match the expected value.

warn: Exit code 1 from powershell
verbose: Stack trace:
   at View054533ca9d944545a5d9b023f65230a4.<>c__DisplayClass3c.<RenderViewLevel0>b__24() in c:\Users\tdu\AppData\Local\Temp\2\c41074bc79cb4ab4a25884f33774342f-1.cs:line 1
055
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View054533ca9d944545a5d9b023f65230a4.<RenderViewLevel0>b__19() in c:\Users\tdu\AppData\Local\Temp\2\c41074bc79cb4ab4a25884f33774342f-1.cs:line 571
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View054533ca9d944545a5d9b023f65230a4.<RenderViewLevel0>b__11() in c:\Users\tdu\AppData\Local\Temp\2\c41074bc79cb4ab4a25884f33774342f-1.cs:line 427
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)

**Comment by anurse** [comment]
This should be fixed now. Pull the latest from dev. Just some fall out from the renames :)
