### ISSUE TITLE
No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.

### ISSUE THREAD

**Issue by shaunluttin** [aspnet/dnvm#291]
This is our `dnvm list` result:

```
Active Version           Runtime Architecture Location                       Alias  
------ -------           ------- ------------ --------                       -----  
       1.0.0-beta4       clr     x64          C:\Users\BigFont\.dnx\runtimes        
  *    1.0.0-beta4       clr     x86          C:\Users\BigFont\.dnx\runtimes        
       1.0.0-beta4       coreclr x64          C:\Users\BigFont\.dnx\runtimes        
       1.0.0-beta4       coreclr x86          C:\Users\BigFont\.dnx\runtimes        
       1.0.0-beta6-12005 clr     x86          C:\Users\BigFont\.dnx\runtimes default
```

This is what we get when we run `dnx . web` from the `\GitHub\Security\samples\CookieSample` directory after a fresh clone.

```
dnx : System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
At line:1 char:1
+ dnx . web 2>&1 | out-file result.txt
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO...een registered.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
```

**Comment by mleanos** [comment]
@shanselman Did you figure this out? I'm having the same issue, with the later dnvm versions.

**Comment by shaunluttin** [comment]
@mleanos That was several months ago and I'm afraid we've forgotten how we resolved it.
